"""add dwh star schema tables

Revision ID: 8df4d27d7c4b
Revises: 942b014373ce
Create Date: 2026-05-31 14:19:25.558991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df4d27d7c4b'
down_revision = '942b014373ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dwh_dim_category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('dwh_dim_date',
    sa.Column('date_id', sa.String(length=8), nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('month_name', sa.String(length=20), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.String(length=10), nullable=True),
    sa.Column('is_weekend', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('date_id')
    )
    op.create_table('dwh_dim_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('dwh_dim_wallet',
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('wallet_id')
    )
    op.create_table('dwh_fact_transaction',
    sa.Column('fact_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('date_id', sa.String(length=8), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=True),
    sa.Column('usd_rate_at_date', sa.Float(), nullable=True),
    sa.Column('erosi_persen', sa.Float(), nullable=True),
    sa.Column('etl_loaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['dwh_dim_category.category_id'], ),
    sa.ForeignKeyConstraint(['date_id'], ['dwh_dim_date.date_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dwh_dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['dwh_dim_wallet.wallet_id'], ),
    sa.PrimaryKeyConstraint('fact_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dwh_fact_transaction')
    op.drop_table('dwh_dim_wallet')
    op.drop_table('dwh_dim_user')
    op.drop_table('dwh_dim_date')
    op.drop_table('dwh_dim_category')
    # ### end Alembic commands ###
